# Generated by Django 4.1.9 on 2023-06-09 20:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spmc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperPixelAlgo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="SuperPixelType name")),
                ("description", models.TextField(blank=True, verbose_name="SuperPixelType description")),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="srid",
            field=models.IntegerField(default=3857),
        ),
        migrations.AddField(
            model_name="scene",
            name="bbox",
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="scene",
            name="tiles_path",
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scene",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Scene description"),
        ),
        migrations.CreateModel(
            name="SuperPixel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sp", django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ("algo_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="spmc.superpixelalgo")),
                ("scene_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="spmc.scene")),
            ],
        ),
        migrations.CreateModel(
            name="ProjectAlgos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("algo_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="spmc.superpixelalgo")),
                ("proj_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="spmc.project")),
            ],
        ),
        migrations.CreateModel(
            name="MiscTiles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="MiscTiles name")),
                ("description", models.TextField(blank=True, verbose_name="MiscTiles description")),
                ("tiles_path", models.FilePathField(blank=True)),
                ("bbox", django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ("scene_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="spmc.scene")),
            ],
        ),
    ]
