# Generated by Django 4.1.9 on 2023-06-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spmc", "0003_misctile_rename_projectalgos_projectalgo_scene_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="LandClass name")),
                ("description", models.TextField(blank=True, verbose_name="LandClass description")),
                ("color", models.CharField(blank=True, max_length=255, verbose_name="LandClass color")),
            ],
        ),
        migrations.CreateModel(
            name="LandClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="LandClassification name")),
                ("description", models.TextField(blank=True, verbose_name="LandClassification description")),
                ("land_class_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="spmc.landclass")),
                ("project_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="spmc.project")),
            ],
        ),
        migrations.AddField(
            model_name="superpixel",
            name="class_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="spmc.landclass"
            ),
        ),
    ]
