# Generated by Django 4.1.9 on 2023-06-12 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spmc", "0004_landclass_landclassification_superpixel_class_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landclassification",
            name="description",
        ),
        migrations.RemoveField(
            model_name="landclassification",
            name="name",
        ),
    ]
