# Generated by Django 4.1.9 on 2023-06-16 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spmc", "0006_remove_superpixel_class_id_segementationentry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SegementationEntry",
            new_name="SegmentationEntry",
        ),
    ]
